### ISSUE TITLE
UBTU-20-010453 conditional oddly returns false within role when set to true in group_vars.

### ISSUE THREAD

**Issue by kfiresmith** [ansible-lockdown/UBUNTU20-STIG#10]
**Describe the Issue**
For an unknown reason, the UBUNTU20-STIG role ignores ubtu_20_010453 being set to true in group_vars.  Copying the tasks into my own role and leaving everything else the same, the ubtu_20_010453 variable is correctly interpreted as true.

**Expected Behavior**
UBTU-20 role should honor `ubtu_20_010453: true`

**Actual Behavior**
```
TASK [UBUNTU20-STIG : LOW | UBTU-20-010453 | AUDIT | The Ubuntu operating system must display the date and time of the last successful account logon upon logon. | Get pam_lastlog.so showfailed status] ***
task path: /home/foo/ansible-beta/roles/UBUNTU20-STIG/tasks/fix-cat3.yml:627
skipping: [foo.whoi.edu] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}
```

Running the exact same code in my own abbreviated role shows:
```
TASK [kfiresmith.cmmc_controls : LOW | UBTU-20-010453 | PATCH | The Ubuntu operating system must display the date and time of the last successful account logon upon logon. | Set if noshowfail exists] ***
task path: /home/sysadm/ansible-beta/roles/kfiresmith.cmmc_controls/tasks/pam.yml:12
ok: [foo.whoi.edu] => {
    "backupdest": "",
    "change_count": 0,
    "changed": false,
    "invocation": {
        "module_args": {
            "backup": false,
            "control": "required",
            "module_arguments": [
                "showfailed"
            ],
            "module_path": "pam_lastlog.so",
            "name": "login",
            "new_control": null,
            "new_module_path": null,
            "new_type": null,
            "path": "/etc/pam.d",
            "state": "args_present",
            "type": "session"
        }
    }
}
```

**Control(s) Affected**
ubtu_20_010453

**Environment (please complete the following information):**

- branch being used: 2.9.0
- Ansible Version: ansible [core 2.12.10]
- Host Python Version:  Python 2.7.18 
- Ansible Server Python Version: python version = 3.8.10 (default, May 26 2023, 14:05:08) [GCC 9.4.0]
- Additional Details:

**Additional Notes**
Anything additional goes here

**Possible Solution**
Enter a suggested fix here

**Comment by uk-bolly** [comment]
hi @kfiresmith 

Thank you for taking the time to raise this issue, I am confused on how this is occuring. it would be worth adding a debug into the play to see what it thinks the value is.
I am not able to replicate the issue
The only thing i can think it could be is a quoted value in the var meaning its not being see as a boolean but a string so would equal false.
If you could please test a let us know?

many thanks

uk-bolly

**Comment by uk-bolly** [comment]
closing as stale
