### ISSUE TITLE
audit rules template mistake - fdisk

### ISSUE THREAD

**Issue by kfiresmith** [ansible-lockdown/UBUNTU20-STIG#11]
**Describe the Issue**
A path mistake in the audit rules template for Ubuntu 20 causes the audit fdisk check to fail when benchmarking.

The problematic line is https://github.com/ansible-lockdown/UBUNTU20-STIG/blob/0e94b5de1439c772d320d77805bbe05f106f197b/templates/audit/99_stig_auditd.rules.j2#L148

The benchmark check correctly paths fdisk to `/sbin/fdisk`:

```
  <ind:pattern operation="pattern match">^[\s]*-w[\s]+/sbin/fdisk[\s]+-p[\s]+x[\s]+-k[\s]+modules[\s]*$</ind:pattern>
```

**Expected Behavior**
Check should pass

**Actual Behavior**
Check does not pass as the rule is created for `/bin/fdisk` and not `/sbin/fdisk`

**Control(s) Affected**
UBTU-20-010298

**Environment (please complete the following information):**

- branch being used: [e.g. devel]
- Ansible Version: [e.g. 2.10]
- Host Python Version: [e.g. Python 3.7.6]
- Ansible Server Python Version: [e.g. Python 3.7.6]
- Additional Details:

**Additional Notes**
Anything additional goes here

**Possible Solution**
Fix template at line number 148 as permalinked above.
`s/bin/sbin`

**Comment by uk-bolly** [comment]
hi @kfiresmith 

Thank you for raising this issue, I am happy to say that the suggested fix has been added and merged to both devel and main branches.
Unless you have any issue, i believe this could now be closed?

many thanks

uk-bolly
