### ISSUE TITLE
audit rules mistake init/finit

### ISSUE THREAD

**Issue by kfiresmith** [ansible-lockdown/UBUNTU20-STIG#12]
**Describe the Issue**
V-238295 / ubtu_20_010179 doesn't pass SCAP benchmarking because it's missing the init portion.
Rule text:  "The Ubuntu operating system must generate audit records for successful/unsuccessful uses of the init_module and finit_module syscalls."

Lockdown template entries:
```
-a always,exit -F arch=b32 -S finit_module -F auid>=1000 -F auid!=4294967295 -k module_chng
-a always,exit -F arch=b64 -S finit_module -F auid>=1000 -F auid!=4294967295 -k module_chng
```

STIG check passing value:
```
-a always,exit -F arch=b32 -S init_module,finit_module -F auid>=1000 -F auid!=4294967295 -k module_chng
-a always,exit -F arch=b64 -S init_module,finit_module -F auid>=1000 -F auid!=4294967295 -k module_chng
```

**Expected Behavior**
Check should pass after enabling variable for check item

**Actual Behavior**
template just missing `init_module`

**Control(s) Affected**
V-238295 / ubtu_20_010179

**Environment (please complete the following information):**

- branch being used: [e.g. devel]
- Ansible Version: [e.g. 2.10]
- Host Python Version: [e.g. Python 3.7.6]
- Ansible Server Python Version: [e.g. Python 3.7.6]
- Additional Details:

**Additional Notes**
Anything additional goes here

**Possible Solution**
Enter a suggested fix here

**Comment by uk-bolly** [comment]
hi @kfiresmith 

Thank you for raising this issue, I am happy to say that the suggested fix has been added and merged to both devel and main branches.
Unless you have any issue, i believe this could now be closed?

many thanks

uk-bolly
