### ISSUE TITLE
 UBTU-20-010048 is matching the wrong part of /etc/ssh/sshd_config

### ISSUE THREAD

**Issue by alex-rowe** [ansible-lockdown/UBUNTU20-STIG#13]
**Describe the Issue**
In UBTU-20-010048, it's trying to set `X11Forwarding no` but the `regexp` for `lineinfile` is also searching for whitespaces at the beginning of the line. This causes it to match at the end of the file in per user overrides for OpenSSH, not in the global section. This causes automated scans as the `X11Forwarding yes` still exists

**Expected Behavior**
The first `X11Forwarding yes` should be updated, and the second one left as is.

**Actual Behavior**
Reviewing `/etc/ssh/sshd_config` the below is what the file looks like

```
X11Forwarding yes
...
...
# Example of overriding settings on a per-user basis
#Match User anoncvs
X11Forwarding no
#       AllowTcpForwarding no
#       PermitTTY no
#       ForceCommand cvs server
```

**Control(s) Affected**
UBTU-20-010048

**Environment (please complete the following information):**

- branch being used: [e.g. devel] commit 0e94b5de1439c772d320d77805bbe05f106f197b
- Ansible Version: [e.g. 2.10] 2.13.7
- Host Python Version: [e.g. Python 3.7.6]
- Ansible Server Python Version: [e.g. Python 3.7.6]
- Additional Details:

**Additional Notes**
N/A

**Possible Solution**
Changing the regexp to the below should be enough, to remove the `\s*`

```
  ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^#?X11Forwarding'
      line: "X11Forwarding no"
```

**Comment by uk-bolly** [comment]
hi @alex-rowe 

Thank you for raising this issue, I am happy to say that the suggested fix has been added and merged to both devel and main branches.
Unless you have any issue, i believe this could now be closed?

many thanks

uk-bolly

**Comment by alex-rowe** [comment]
I don't think the new regex works as expected as we've disabled it to run our own instead.

Before:
`regexp: '^#?\s*X11Forwarding'`

After
`regexp: '^#?(\s+|)X11Forwarding'`

Config file:
```
...
X11Forwarding VALUE
...
#Match User anoncvs
#	X11Forwarding no
```

`regexp` in Ansible will replace the last match not the first match, so it's probably the same.

We're using `regexp: '^#?X11Forwarding'` instead and it's working for us.

**Comment by uk-bolly** [comment]
hi @alex-rowe 

Thank you again for the feedback, your solution covers more options without changing those that are not required.
I will add this to a new PR

Thank you again

uk-bolly

**Comment by uk-bolly** [comment]
hi @alex-rowe 

I believe this is now completed and merged. I will close this issue, please feel free to reopen of feedback if any problems are seen with this issue.

many thanks 

uk-bolly
